import { pgTable, serial, text, date, timestamp, boolean, integer, index, customType } from 'drizzle-orm/pg-core'

// Custom type for pgvector
const vector = customType<{ data: number[] | null; driverData: string | null }>({
  dataType() {
    return 'vector(1536)'
  },
  toDriver(value: number[] | null): string | null {
    if (value === null || value === undefined) return null
    return `[${value.join(',')}]`
  },
  fromDriver(value: string | null): number[] | null {
    if (value === null || value === undefined) return null
    return JSON.parse(value.replace(/^\[/, '[').replace(/\]$/, ']'))
  },
})

// Note: tsvector columns are auto-generated by PostgreSQL triggers
// and are not directly modeled in Drizzle ORM
import { productCategories } from './product-categories.schema.js'

/**
 * Extended Medicinal Products Schema - ALL EMA Fields
 *
 * Design Principles:
 * - Store ALL fields from EMA JSON (not just subset)
 * - Stable IDs (serial), human-friendly slugs
 * - Denormalized for query performance where appropriate
 * - Provenance tracking (source_url, revision_number, last_updated_date)
 *
 * This extends the Phase 1 schema to capture the complete EMA dataset
 */
export const medicinalProductsExtended = pgTable(
  'medicinal_products_extended',
  {
    // Core Identity
    id: serial('id').primaryKey(),
    slug: text('slug').notNull().unique(),
    name: text('name').notNull(), // name_of_medicine
    emaNumber: text('ema_number').unique(), // ema_product_number (EMEA/H/C/005814)

    // Category
    categoryId: integer('category_id').references(() => productCategories.id),
    category: text('category').notNull(), // 'Human', 'Veterinary' (denormalized for queries)

    // Status Fields
    medicineStatus: text('medicine_status').notNull(), // 'Authorised', 'Withdrawn', etc.
    opinionStatus: text('opinion_status'), // Can be empty

    // Active Substances
    internationalNonProprietaryName: text('international_non_proprietary_name'), // INN/common name (semicolon-separated)
    activeSubstance: text('active_substance'), // Often same as INN (semicolon-separated)

    // Therapeutic Classification
    therapeuticAreaMesh: text('therapeutic_area_mesh'), // MeSH terms
    therapeuticIndication: text('therapeutic_indication'), // Full text indication
    atcCode: text('atc_code'), // ATC classification
    pharmacotherapeuticGroup: text('pharmacotherapeutic_group'), // Human or Veterinary specific

    // Product Designations (Boolean Flags)
    patientSafety: boolean('patient_safety').default(false),
    acceleratedAssessment: boolean('accelerated_assessment').default(false),
    additionalMonitoring: boolean('additional_monitoring').default(false),
    advancedTherapy: boolean('advanced_therapy').default(false),
    biosimilar: boolean('biosimilar').default(false),
    conditionalApproval: boolean('conditional_approval').default(false),
    exceptionalCircumstances: boolean('exceptional_circumstances').default(false),
    genericOrHybrid: boolean('generic_or_hybrid').default(false),
    orphanMedicine: boolean('orphan_medicine').default(false),
    primePriorityMedicine: boolean('prime_priority_medicine').default(false),

    // Company (Denormalized - actual relationships in product_companies)
    marketingAuthorisationHolderDeveloperApplicant: text('marketing_authorisation_holder_developer_applicant'),

    // Key Dates
    opinionAdoptedDate: date('opinion_adopted_date'),
    europeanCommissionDecisionDate: date('european_commission_decision_date'),
    marketingAuthorisationDate: date('marketing_authorisation_date'),
    withdrawalExpiryRevocationLapseDate: date('withdrawal_expiry_revocation_lapse_date'),
    firstPublishedDate: date('first_published_date'),
    lastUpdatedDate: date('last_updated_date'),

    // Procedures
    latestProcedureAffectingProductInformation: text('latest_procedure_affecting_product_information'), // e.g., VR/0000254621

    // Provenance & Versioning
    revisionNumber: integer('revision_number'), // From EMA JSON
    medicineUrl: text('medicine_url'), // Source URL
    sourceEmaSourceId: integer('source_ema_source_id'), // Which crawl source?

    // Search & Embeddings
    embedding: vector('embedding'),
    searchText: text('search_text'),
    embeddingUpdatedAt: timestamp('embedding_updated_at'),
    // searchTsv is a generated column, read via raw SQL

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => [
    index('medicinal_products_ext_status_idx').on(table.medicineStatus),
    index('medicinal_products_ext_category_idx').on(table.category),
    index('medicinal_products_ext_name_idx').on(table.name),
    index('medicinal_products_ext_atc_idx').on(table.atcCode),
    index('medicinal_products_ext_orphan_idx').on(table.orphanMedicine),
    index('medicinal_products_ext_updated_idx').on(table.lastUpdatedDate),
  ]
)

export type MedicinalProductExtended = typeof medicinalProductsExtended.$inferSelect
export type NewMedicinalProductExtended = typeof medicinalProductsExtended.$inferInsert
